services:
  ratchetup_candidate:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ratchetup_candidate
    environment:
      - VIRTUAL_HOST=candidate.ratchetup.ai,ratchetup.ai
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=candidate.ratchetup.ai,ratchetup.ai
      - LETSENCRYPT_EMAIL=isaac.ochieng2000@gmail.com
    expose:
      - "80"
    networks:
      - proxy
    restart: unless-stopped
networks:
  proxy:
    external: true
